UI basic setup
cha2251/rit-player-piano pull request #23
Opened 2023-01-22 22:43 UTC by dsp9049

2023-01-24 22:27 UTC, cha2251 requested changes

2023-01-24 22:27 UTC, cha2251 commented on src/user_interface/home_page.py
> +        self.lambda_thing = None
What dis

2023-01-24 22:27 UTC, cha2251 commented on src/user_interface/home_page.py
> +        # title.setAlignment(Qt.AlignTop)
Delete this

2023-01-24 22:27 UTC, cha2251 commented on src/user_interface/main_page.py
> +    app = QApplication([])
Can we make this a fucntion in this class that gets called from main.py?
that way everything runs through `python -m src.common.main`

2023-01-26 20:28 UTC, DavidTheFighter commented
Also, the image files used in the UI are currently inside the source directory. This means if I run the program with the usual `python -m src.user_interface.main_page` they won't get picked up. Do we want to move these to the top-level directory?

2023-01-26 21:11 UTC, dsp9049 commented on src/user_interface/home_page.py
> +        self.lambda_thing = None
fixed in latest version

2023-01-26 21:11 UTC, dsp9049 commented on src/user_interface/home_page.py
> +        # title.setAlignment(Qt.AlignTop)
deleted

2023-01-26 23:12 UTC, cha2251 approved these changes
lgtm

2023-01-30 15:10 UTC, merged